name: dermalens
description: "Be the better version of you"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  shadcn_flutter: ^0.0.24
  supabase_flutter: ^2.8.4
  tflite_flutter: ^0.11.0
  http: ^1.3.0
  shared_preferences: ^2.2.0
  provider: ^6.1.2
  intl: ^0.20.2
  uuid: ^4.5.1
  image: ^4.5.4
  path_provider: ^2.1.5
  google_mlkit_face_detection: ^0.13.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



flutter_launcher_icons:
  android: "launcher_icon"   # Nama ikon untuk Android
  ios: true                  # Aktifkan untuk iOS
  image_path: "assets/icons/app_icon.png" # Path ke file ikon utama Anda
  min_sdk_android: 21        # (Opsional) Sesuaikan dengan minSdkVersion Anda jika perlu
  remove_alpha_ios: true     # (Opsional) Menghapus channel alpha untuk ikon iOS

flutter:
  uses-material-design: true

  assets:
    - assets/avatars/
    - assets/model/
    - assets/icons/
    - assets/images/

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Black.ttf
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
        - asset: assets/fonts/LeagueSpartan-ExtraBold.ttf
        - asset: assets/fonts/LeagueSpartan-ExtraLight.ttf
        - asset: assets/fonts/LeagueSpartan-Light.ttf
        - asset: assets/fonts/LeagueSpartan-Medium.ttf
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
        - asset: assets/fonts/LeagueSpartan-SemiBold.ttf
        - asset: assets/fonts/LeagueSpartan-Thin.ttf